### ISSUE TITLE
Highlight module leaks memory

### ISSUE THREAD

**Issue by jlombera** [nvim-treesitter/nvim-treesitter#1029]
**Describe the bug**

nvim-treesitter's highlight module leaks memory.  Every time a buffer is reloaded, e.g. with `:e`, the memory consumption of nvim increases.  This memory is never released, not even after deleting the buffer with `:bwipeout`.

**To Reproduce**

Minimal `vimrc` that reproduces the problem:
<details>

```vim
call plug#begin('~/.local/share/nvim/pluggen')
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
call plug#end()

lua << EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true
  }
}
EOF
```
</details>

1. Open a file for which nvim-treesitter syntax highlighting has been enabled.
2. Reload the file several time, e.g. with `:e`.
3. Observe how memory used by nvim increases every time the buffer is reloaded.
4. Delete the buffer with `:bwipeout`.
5. Observe memory is still in use.

**Expected behavior**

Memory used by nvim-treesitter for a given buffer should be freed when the buffer is reloaded/deleted.

**Output of `:checkhealth nvim_treesitter`**

<details>

```
health#nvim_treesitter#check
=======================================================================
## Installation
  - OK: `tree-sitter` found  0.19.3 (f3910c649e5c90438e6a86a7d29e4554ca7aeb12)(parser generator, used for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found.

## Parser/Features H L F I
  - c              ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓
 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         *) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```
</details>

**Output of `nvim --version`**

<details>

```
NVIM v0.5.0-dev+1133-g0869cbd55
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az49-948

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

```
</details>

**Additional context**

- nvim-treesitter version: e4083fc
- I tested —and was able to reproduce— with C and Python files.
- The bigger the file, the easier it is to observe the issue (since memory consumption increases faster).

**Comment by kyazdani42** [comment]
@vigoux is this an upstream bug ? i tried doing a `ts.highlighter.active[bufnr]` check when attaching but it says it's nil although the buffer does exists and is actively highlighted with treesitter.
Also it seems the module detach function is not called when deleting/wiping a buffer which results in treesitter still loaded in memory.

**Comment by vigoux** [comment]
I think that might come from both us and upstream, I'll try to dig into that.

**Comment by kyazdani42** [comment]
alright, indeed from this end we do not check the highlighter is active before loading it but in any case nvim should not reload the parser for the same buffer twice. For the unloading part, not sure if this should be done through neovim or us though.

**Comment by vigoux** [comment]
From what I remember, we don't do very much from our end on the highlighting part, so most of the work should be done by nvim upstream.

**Comment by chentau** [comment]
@jlombera Can you build Neovim with ASAN enabled, and post the logs? That would help a lot.

**Comment by jlombera** [comment]
@chentau Not sure this is what you expected (I'm not familiar with ASAN), but here is some output I was able to generate:
```
$ cat ~/test.vim 
call plug#begin('~/.local/share/nvim/pluggen')
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
call plug#end()

lua << EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true
  }
}
EOF

$ wc -l ~/file2.py 
32768 /home/jlombera/file2.py

$ ./build/bin/nvim --version
NVIM v0.5.0-dev
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -fno-sanitize-recover=all -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address -fsanitize=undefined -fsanitize-blacklist=/home/jlombera/downloads/neovim-nightly/src/.asan-blacklist -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -DEXITFREE -I/home/jlombera/downloads/neovim-nightly/build/config -I/home/jlombera/downloads/neovim-nightly/src -I/home/jlombera/downloads/neovim-nightly/.deps/usr/include -I/usr/include -I/home/jlombera/downloads/neovim-nightly/build/src/nvim/auto -I/home/jlombera/downloads/neovim-nightly/build/include
Compiled by jlombera@debian

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
     fall-back for $VIM: "/home/jlombera/usr/stow/nvim-0.5-dev-src/share/nvim"

     Run :checkhealth for more info


$ ASAN_OPTIONS=detect_leaks=1 ./build/bin/nvim -u ~/test.vim ~/file2.py +q

=================================================================
==44721==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 640 byte(s) in 1 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e55e62 in ts_query_cursor_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e55e62)
    #2 0x1e8a18c in lj_BC_FUNCC (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e8a18c)

Indirect leak of 11009952 byte(s) in 114687 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e59547 in ts_stack_pop_count (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e59547)

Indirect leak of 3932160 byte(s) in 49152 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e5dbf0 in ts_subtree_new_leaf (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e5dbf0)

Indirect leak of 32768 byte(s) in 1 object(s) allocated from:
    #0 0x4e3409 in realloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e3409)
    #1 0x1e5e5f5 in ts_subtree_balance (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e5e5f5)

Indirect leak of 2784 byte(s) in 12 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e58919 in ts_stack_push (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e58919)

Indirect leak of 1456 byte(s) in 1 object(s) allocated from:
    #0 0x4e3262 in calloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e3262)
    #1 0x1e4a4f6 in ts_parser_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e4a4f6)
    #2 0x1e8a18c in lj_BC_FUNCC (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e8a18c)

Indirect leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x4e3409 in realloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e3409)
    #1 0x1e61053 in ts_tree_cursor_goto_first_child (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e61053)

Indirect leak of 576 byte(s) in 1 object(s) allocated from:
    #0 0x4e3409 in realloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e3409)
    #1 0x1e54b40 in ts_query__parse_pattern (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e54b40)
    #2 0x7fd836968baf  (<unknown module>)

Indirect leak of 512 byte(s) in 1 object(s) allocated from:
    #0 0x4e3409 in realloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e3409)
    #1 0x1e538b1 in ts_query__parse_predicate (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e538b1)

Indirect leak of 400 byte(s) in 1 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e5c227 in ts_stack_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e5c227)

Indirect leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e5d88c in ts_subtree_pool_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e5d88c)

Indirect leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x4e3409 in realloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e3409)
    #1 0x1e542e0 in ts_query__parse_pattern (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e542e0)
    #2 0x7fd836968baf  (<unknown module>)

Indirect leak of 232 byte(s) in 1 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e5c24d in ts_stack_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e5c24d)

Indirect leak of 176 byte(s) in 1 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e552ac in ts_query_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e552ac)

Indirect leak of 160 byte(s) in 1 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e5c1c5 in ts_stack_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e5c1c5)

Indirect leak of 160 byte(s) in 1 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e55908 in ts_query_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e55908)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e55ec6 in ts_query_cursor_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e55ec6)
    #2 0x1e8a18c in lj_BC_FUNCC (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e8a18c)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e5c206 in ts_stack_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e5c206)

Indirect leak of 128 byte(s) in 2 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e4efec in symbol_table_insert_name.part.0 (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e4efec)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e55ee3 in ts_query_cursor_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e55ee3)
    #2 0x1e8a18c in lj_BC_FUNCC (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e8a18c)

Indirect leak of 96 byte(s) in 1 object(s) allocated from:
    #0 0x4e3409 in realloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e3409)
    #1 0x1e5eaa8 in ts_subtree_new_node (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e5eaa8)

Indirect leak of 96 byte(s) in 1 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e5c1e5 in ts_stack_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e5c1e5)

Indirect leak of 96 byte(s) in 2 object(s) allocated from:
    #0 0x4e3409 in realloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e3409)
    #1 0x1e4efb2 in symbol_table_insert_name.part.0 (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e4efb2)

Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x4e3262 in calloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e3262)
    #1 0x1e5c178 in ts_stack_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e5c178)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e4a52c in ts_parser_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e4a52c)
    #2 0x1e8a18c in lj_BC_FUNCC (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e8a18c)

Indirect leak of 53 byte(s) in 3 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x7fd834e690b4 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xa60b4)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x4e30ed in malloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e30ed)
    #1 0x1e605ec in ts_tree_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e605ec)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x4e3262 in calloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e3262)
    #1 0x1e6061a in ts_tree_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e6061a)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x4e3409 in realloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e3409)
    #1 0x1e6518e in ts_lexer_set_included_ranges (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e6518e)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x4e3409 in realloc (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x4e3409)
    #1 0x1e5568a in ts_query_new (/home/jlombera/downloads/neovim-nightly/build/bin/nvim+0x1e5568a)

SUMMARY: AddressSanitizer: 14984629 byte(s) leaked in 163882 allocation(s).
```

**Comment by kyazdani42** [comment]
closing since i think it's not an issue anymore. Ping me if you can still reproduce with nvim > 0.7
