### ISSUE TITLE
Problem with Windows when install

### ISSUE THREAD

**Issue by BeLeap** [nvim-treesitter/nvim-treesitter#1699]
**Describe the bug**

It fails to install (see additional context)

**To Reproduce**

1. Run `:TSInstall c`

**Expected behavior**

It installs well

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found Active code page: 437 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `clang` executable found. Selected from { "clang", "gcc" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - cpp            ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

❯ nvim --version
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-786

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

![image](https://user-images.githubusercontent.com/46488521/129474260-6fb59b8b-a24e-41a8-9901-bbda2d908f03.png)

**Comment by uncomfyhalomacro** [comment]
I also have the same problem.

**Comment by vigoux** [comment]
Could you try running `:TSInstallSync` instead of `TSInstall` just to see ?

**Comment by BeLeap** [comment]
![image](https://user-images.githubusercontent.com/46488521/129561995-a63a6b90-d8da-4a39-99f8-c43dd029a9fa.png)
The same error occurs. (The message is broken because I am using the Korean version of Windows, but the message was the same when I changed it to English last time.)
@vigoux

**Comment by vmuthuk2** [comment]
I have the same issue as well. Irrespective of the language.
![image](https://user-images.githubusercontent.com/25335803/130123038-f2848ac4-43fa-4340-91a2-600cc2de70cd.png)

**Comment by vigoux** [comment]
Could you try to follow this instructions [here](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support) and see if that fixes your issue ?

**Comment by BeLeap** [comment]
I already followed it

**Comment by vigoux** [comment]
Then check if `tree-sitter` is in your path, to be sure. None of us is a windows expert actually, so I guess you will have to do some debugging on your end.

**Comment by dutchgecko** [comment]
I'm also running into this. The first screenshot includes the same error line as what I'm seeing:

    The process cannot access the file because it is being used by another process.

It looks like the script is trying to remove a directory that's already been opened by the nvim process. On other operating systems this would work fine, but under Windows this is an error as Windows does not permit any type of writes to files in use.

**Comment by kmiasko** [comment]
Same problem here. As @dutchgecko said, git.exe is locking the files / directories.

**Comment by dutchgecko** [comment]
This appears to be a bug in an older version of Git for Windows. By chance I came across an error message while trying to use Git in a Windows environment (usually I'm on WSL), which led me to [this stackexchange post](https://stackoverflow.com/a/69018027/1732797). It turned out I did have version 2.32 installed, and upgrading to the latest version fixed this installer issue for me.

**Comment by theHamsta** [comment]
@dutchgecko can you put that into our wiki? Also, would curl installation for Windows be preferable in general?

**Comment by dutchgecko** [comment]
@theHamsta I'd like to wait to see if upgrading git works for the other people having the same issue here, if it's a confirmed fix then I'd be happy to add it to the wiki.

I think git is fine for installation, since pretty much all neovim users will have it installed for plugin management. `curl` is built into windows now, which is nice, but afaik there's no command line unzipping tool provided as standard, so you end up with another dependency that way. I'm no windows expert though, perhaps some powershell gurus can chime in with what's possible.

**Comment by theHamsta** [comment]
curl is shipped with nvim and BSD tar on new enough versions of Windows 10. There were only a few problems with older versions of Windows 10.

**Comment by kmiasko** [comment]
@dutchgecko Upgrade from 2.32 to 2.34 did the trick for me. Thanks.

**Comment by xaviernogueira** [comment]
I am having the same issue. Something I tried (to not avail):
* Updating git
* Using admin shell

**Comment by gcardozo123** [comment]
After adding the cl.exe compiler folder to my PATH I started to get errors when opening nvim. 
I tried to setup Visual Studio 2022 console variables (PATH, LIB and INCLUDE) as mentioned [here](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support#msvc) but that doesn't seem to help.

It's curious that the error message being printed 
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32215 for x64^M
Copyright (C) Microsoft Corporation.  All rights reserved.
```
is the same message that appears when you run `cl.exe`. Which makes me think that _maybe_ treesitter is passing some argument that cl.exe doesn't understand. 

These are all messages I get:
```
nvim-treesitter[lua]: Error during compilation
Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32215 for x64^M
Copyright (C) Microsoft Corporation.  All rights reserved.^M
^M

Press ENTER or type command to continue
[nvim-treesitter] [1/11, failed: 1] Compiling...
Press ENTER or type command to continue
[nvim-treesitter] [1/11, failed: 1] Checking out locked revision
Press ENTER or type command to continue
parser.c^M
Press ENTER or type command to continue
Microsoft (R) Incremental Linker Version 14.35.32215.0^M
Press ENTER or type command to continue
Copyright (C) Microsoft Corporation.  All rights reserved.^M
Press ENTER or type command to continue
^M
Press ENTER or type command to continue
/out:parser.so ^M
Press ENTER or type command to continue
/dll ^M
Press ENTER or type command to continue
/implib:parser.lib ^M
Press ENTER or type command to continue
parser.obj ^M
Press ENTER or type command to continue
   Creating library parser.lib and object parser.exp^M
Press ENTER or type command to continue
LINK : error LNK2001: unresolved external symbol _DllMainCRTStartup^M
Press ENTER or type command to continue
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\lib\x86\LIBCMT.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'^M
Press ENTER or type command to continue
parser.so : fatal error LNK1120: 1 unresolved externals^M
Press ENTER or type command to continue
Press ENTER or type command to continue
nvim-treesitter[vimdoc]: Error during compilation
Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32215 for x64^M
Copyright (C) Microsoft Corporation.  All rights reserved.^M
^M

Press ENTER or type command to continue
```

**Comment by xaviernogueira** [comment]
I solved my issue by switching to WSL. The underlying issue still exists.

**Comment by odCat** [comment]
I solved my issue by removing the .so files from the folder: AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\parser

Then nvim compiled new ones at launch. Everything seems to be working now.

**Comment by lthnh** [comment]
I can confirm this issue still exist on Windows 11. I have the latest version of Git.
```
PS C:\Users\{username}\AppData\Local\nvim-data> git --version
git version 2.43.0.windows.1
```

**Comment by lthnh** [comment]
Okay, I also have this issue when on Windows 11. The error message is the same as above but without this line:
```The process cannot access the file because it is being used by another process.```
Turns out it's my `cmd` that broke. I try to run `cmd` from run and it has output exit code 1. So I search around and find this StackOverflow link: [](https://stackoverflow.com/questions/66335300/cmd-crashes-with-exit-code-1-after-uninstalling-anaconda). Following the guide do help me fix my issue.
Hope this help others like me in the future.

**Comment by talesofterror** [comment]
installing mingw with chocolatey ("choco install mingw") from an administrator powershell fixed the issue for me.

**Comment by zongpingding** [comment]
> Could you try running `:TSInstallSync` instead of `TSInstall` just to see ?

This solve my problem,thanks !

**Comment by kmoschcau** [comment]
Hi, I'm also having this problem and I think this is because I have powershell configured as the shell to use for neovim. My configuration for it looks like this:

```lua
local has_pwsh = vim.fn.executable "pwsh"
local has_powershell = vim.fn.executable "powershell"
if vim.fn.has "win32" == 1 and (has_pwsh or has_powershell) then
  vim.o.shell = has_pwsh and "pwsh" or "powershell"
  vim.o.shellcmdflag = "-NoLogo"
    .. " -NonInteractive"
    .. " -ExecutionPolicy RemoteSigned"
    .. " -Command [Console]::InputEncoding = [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()"
    .. "; $PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'"
    .. "; $PSStyle.OutputRendering = 'plaintext'"
    .. "; Remove-Alias -Force -ErrorAction SilentlyContinue tee"
    .. ";"
  vim.o.shellredir = '2>&1 | %%{ "$_" } | Out-File %s; exit $LastExitCode'
  vim.o.shellpipe = '2>&1 | %%{ "$_" } | tee %s; exit $LastExitCode'
  vim.o.shellquote = ""
  vim.o.shellxquote = ""
end
```

I can reliably reproduce the error by running `:TSInstallSync editorconfig`. When I remove the above section from my config, the command works. Here is the output I get when it errors.
```
editorconfig parser already available: would you like to reinstall ? y/n: y

Unhandled exception. System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.WinGet.CommandNotFound.WinGetCommandNotFoundFeedbackPredictor.WarmUp()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Failed to execute the following command:
{
  cmd = "cmd",
  opts = {
    args = { "/C", "if", "exist", "C:\\Users\\KaiMoschcau\\AppData\\Local\\nvim-data\\tree-sitter-editorconfig", "rmdir", "/s", "/q", "C:\\Users\\KaiMoschcau\\AppData\\Local\\nvim-data\\tree-sitter-editorconfig" }
  }
}
```

**Comment by fruityvince** [comment]
what actually did the trick for me was to delete AppData\Local\nvim-data, to force reinstalling everything. Looks like I had some files locked by windows, which is what was causing the error. Also took a reboot to be able to delete nvim-data

**Comment by FlippingBinary** [comment]
This still happens, especially when bootstrapping an existing NeoVim configuration that triggers a bunch of installs. For example, Zig held a file open for no apparent reason in my case. I'm not sure why the process didn't end until I closed NeoVim, but the folder could not be deleted until it was. Perhaps Zig doesn't explicitly close files and the handle to the process wasn't explicitly destroyed by NeoVim? I don't know if that would explain it.

If there's no way to ensure all files within the folder are closed before attempting to delete it, the best alternative solution to this problem is for `nvim-treesitter` to rename the directory to something that can be found with pattern matching instead of deleting it directly (e.g. `tree-sitter-rust` becomes `.trash-202505210944-tree-sitter-rust`). If that fails, throw an error immediately -- it's probably a permissions problem. At the end of the install, it can attempt to delete any folder named `.trash-*` and suppress errors. The delete might not succeed, but the file will eventually be closed when the host NeoVim closes, and nothing will open it up from the new location, so the next install will succeed in deleting the folder.

Implementing that approach could be fairly simple by changing the command generated by [`select_install_rm_cmd`](https://github.com/nvim-treesitter/nvim-treesitter/blob/066fd6505377e3fd4aa219e61ce94c2b8bdb0b79/lua/nvim-treesitter/shell_command_selectors.lua#L180-L201) so it produces a rename command instead. Then, a pattern-matching delete could be issued somewhere else, perhaps at the end of the [`install` function](https://github.com/nvim-treesitter/nvim-treesitter/blob/066fd6505377e3fd4aa219e61ce94c2b8bdb0b79/lua/nvim-treesitter/install.lua#L504-L555), with a test ensuring it only runs on Windows so this fix has no impact on other platforms.

**Comment by clason** [comment]
Sorry, but all this functionality has already been rewritten (and much simplified). Please try the main branch; the master branch is now irrevocably frozen.

**Comment by FlippingBinary** [comment]
Ahh, I see. I'll override the default branch to use `main` and see how that goes. The code in that branch does look a whole lot cleaner!
