### ISSUE TITLE
Crash in dart file when removing semicolon / writing any symbol except semilocon

### ISSUE THREAD

**Issue by Liverm0r** [nvim-treesitter/nvim-treesitter#2961]
### Describe the bug

When dart code doesn't have a semicolon, vim crashes. 

### To Reproduce

1. Create empty file;
2. Run `:set ft=dart`;
3. Write any symbol except semicolon.

### Expected behavior

Vim doesn't crash.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - json           ✓ ✓ ✓ ✓ . 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - markdown       ✓ . ✓ . ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - kotlin         ✓ ✓ ✓ . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```
```


### Output of `nvim --version`

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.0/share/nvim"
```

**Comment by br1anchen** [comment]
I think this might be caused by [parser](https://github.com/UserNobody14/tree-sitter-dart). I disabled `dart` from `tree-sitter` and used [dart-vim-plugin](https://github.com/dart-lang/dart-vim-plugin) instead.

**Comment by theHamsta** [comment]
@UserNobody

**Comment by theHamsta** [comment]
Does GDB report a segfault in the parser? Or in Neovim. Best compile Neovim and the parser with debug symbols

**Comment by theHamsta** [comment]
Could you please give an example text to enter? Neovim doesn't crash for me.

**Comment by theHamsta** [comment]
for me fuzzing is crashing when initializing queries
```
tree-sitter on  master [?] via 🦀 v1.63.0-nightly 
❯ ln -s /home/stephan/projects/tree-sitter-dart ./test/fixtures/grammars/dart # in tree-sitter repo

tree-sitter on  master [?] via 🦀 v1.63.0-nightly 
❯ export LIB_FUZZER_PATH=/usr/lib/llvm-15/lib/libFuzzer.a                                                      


tree-sitter on  master [?] via 🦀 v1.63.0-nightly 
❯ mkdir out

tree-sitter on  master [?] via 🦀 v1.63.0-nightly 
❯ ./script/build-fuzzers
make: Nothing to be done for 'all'.
Building dart fuzzer...
  File "/home/stephan/tree-sitter/test/fuzz/gen-dict.py", line 28
    print '"%s"' % ''.join(['\\x%02x' % ord(b) for b in lit.encode('utf-8')])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

tree-sitter on  master [?] via 🦀 v1.63.0-nightly 
❯ vi script/build-fuzzers  # changing "python" in script to python2

tree-sitter on  master [!?] via 🦀 v1.63.0-nightly took 5s 
❯ ./script/build-fuzzers 
make: Nothing to be done for 'all'.
Building dart fuzzer...

tree-sitter on  master [!?] via 🦀 v1.63.0-nightly 
❯ ./out/dart_fuzzer 
AddressSanitizer:DEADLYSIGNAL
=================================================================
==8212==ERROR: AddressSanitizer: SEGV on unknown address 0x000900000015 (pc 0x55db035e0a60 bp 0x000000000000 sp 0x7ffcee6d74f0 T0)
==8212==The signal is caused by a READ memory access.
    #0 0x55db035e0a60 in ts_language_symbol_for_name (/home/stephan/tree-sitter/out/dart_fuzzer+0x1bda60) (BuildId: bf13d2129aeb47ca3706113cf4f8281902585213)
    #1 0x55db035ce792 in ts_query__parse_pattern query.c
    #2 0x55db035c9f3b in ts_query_new (/home/stephan/tree-sitter/out/dart_fuzzer+0x1a6f3b) (BuildId: bf13d2129aeb47ca3706113cf4f8281902585213)
    #3 0x55db0357a10d in LLVMFuzzerInitialize (/home/stephan/tree-sitter/out/dart_fuzzer+0x15710d) (BuildId: bf13d2129aeb47ca3706113cf4f8281902585213)
    #4 0x55db0348bc18 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/stephan/tree-sitter/out/dart_fuzzer+0x68c18) (BuildId: bf13d2129aeb47ca3706113cf4f8281902585213)
    #5 0x55db034b74e2 in main (/home/stephan/tree-sitter/out/dart_fuzzer+0x944e2) (BuildId: bf13d2129aeb47ca3706113cf4f8281902585213)
    #6 0x7f10d3710d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #7 0x7f10d3710e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #8 0x55db03482b14 in _start (/home/stephan/tree-sitter/out/dart_fuzzer+0x5fb14) (BuildId: bf13d2129aeb47ca3706113cf4f8281902585213)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/stephan/tree-sitter/out/dart_fuzzer+0x1bda60) (BuildId: bf13d2129aeb47ca3706113cf4f8281902585213) in ts_language_symbol_for_name
==8212==ABORTING

```

**Comment by momrak** [comment]
I have the same issue. Going into an existing dart file works, but when creating a new it will crash with neovim segmentation fault once I enter a character. When reopening the file I get the output as in the image
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/6552049/170457631-91e44280-22b6-4a01-996a-8701b115b54f.png">

**Comment by theHamsta** [comment]
Closing in favor for https://github.com/nvim-treesitter/nvim-treesitter/issues/2972 . I think I've found the first bad commit there

**Comment by Kavantix** [comment]
@theHamsta is there any way I can confirm it is using the correct commit for the dart parser?
I tried setting it in the lock file and TSInstall dart but it still crashes

**Comment by marcusatiliusregulus** [comment]
2972 is not fixed. i closed it because i was asked to do so and expected the broken commit in tree-sitter-dart to be fixed or reverted. however the devs of tree-sitter-dart don't seem to intend to put a working commit at the top of their commit history soon :(

**Comment by amit-ug** [comment]
@marcusatiliusregulus what is the convention in TS for referring to "stable" versions of TS-extensions? Can TS refer to the latest known-to-be-working dart commit instead?
Thanks!

**Comment by marcusatiliusregulus** [comment]
youll have to ask the ts devs that

**Comment by vigoux** [comment]
So, from what I see from here, we would have the find the last working revision of the parser, and put that into the lockfile.
The setup is not that problematic, but we'd also have to tell the CI to ignore the updates on this parser too.

We'll happily accept PRs for this, as this should not involve that much knowlede.

**Comment by marcusatiliusregulus** [comment]
i believe this would just end up pinning parsers to old versions, forgotten to be updated to the latest release. this shouldn't be handled by nvim-treesitter. but maybe nvim-treesitter could ask grammer devs to put release tags or release branches in their repos?

**Comment by Kavantix** [comment]
I've spent some quite time attempting to resolve the issue but haven't been able to find a reliable fix or a good reason for why it's crashing.
On the side I also started on implementing a dart grammar from scratch mostly to better understand how it works. If anyone is interested in spending some time in trying to fix it I'd be willing to meet up and explain what I learned and tried so far.

**Comment by akinsho** [comment]
@Kavantix historically, some of the crashes I hit were caused by the highlight queries being used by nvim-treesitter in the `highlights.scm` I haven't looked at the issue at all, but I'm wondering if there are any invalid nodes still in our `highlights.scm` that were changed in more recent versions of the dart grammar?

It could also just be completely unrelated to that just recounting the most common previous cause of crashes I encountered.

**Comment by Kavantix** [comment]
@akinsho just parsing an empty file crashes, so it has nothing to do with highlighting in this case

**Comment by vigoux** [comment]
I never write a single line of dart but:
> @akinsho just parsing an empty file crashes, so it has nothing to do with highlighting in this case

Do you have a file triggering this somehow, I cant reproduce using the parser directly ?

**Comment by Kavantix** [comment]
Perhaps not an empty file, but I test using a file that only has a few whitelines and some gibberish like `dhdhdhd`

**Comment by vigoux** [comment]
For the record, the reproducer file is:
```

d
```

**Comment by akinsho** [comment]
> On the side I also started on implementing a dart grammar from scratch mostly to better understand how it works

Regarding this, if you read through the issues in treesitter dart, that project desperately needs contributions. Not to say that making a separate project couldn't be better or valuable, but I think if you could possibly contribute so that there is one de facto grammar that gets all the fixes and features I think that would be massively valuable. The maintainer of the current grammar is open to adding people as contributors, so he'd be open to taking any contributions or refactors (granted they don't break other use cases for the grammar)
