### ISSUE TITLE
Neovim segfaults when editing a vue file

### ISSUE THREAD

**Issue by eankorins** [nvim-treesitter/nvim-treesitter#6628]
### Describe the bug

After updating to the latest available version of neovim and tree-sitter neovim exits with a segfault when editing .vue files.

I've tried TSUpdate, says all parsers are up-to-date
When removing the language from treesitter it works fine. 

### To Reproduce

Able to reproduce with vue grammar only installed and  a simple Test.vue file, not in any project just standalone.
```html
<template>
  <div>
  </div>
</template>
```
To reproduce I simply have to add a new line, maybe delete the div element. Most of the time 'O' to insert new line is enough.

Here's the stacktrace I can get from the core dump:
```gdb
#0  0x00007fd590433025 in free () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7fd59038f740 (LWP 61126))]
(gdb) bt
#0  0x00007fd590433025 in free () from /usr/lib/libc.so.6
#1  0x00007fd5907e74c4 in tree_sitter_vue_external_scanner_destroy () from /home/ea/.local/share/nvim/lazy/nvim-treesitter/parser/vue.so
#2  0x00007fd59076a0c6 in ts_parser__external_scanner_destroy (self=0x55c5ead70ee0) at lib/src/parser.c:383
#3  ts_parser_reset (self=self@entry=0x55c5ead70ee0) at lib/src/parser.c:1970
#4  0x00007fd59076a7b5 in ts_parser_parse (self=<optimized out>, old_tree=old_tree@entry=0x55c5ead52d70, input=...) at lib/src/parser.c:2114
#5  0x000055c5e8a71bb7 in parser_parse (L=0x7fd59036f380) at /usr/src/debug/neovim/neovim-0.9.5/src/nvim/lua/treesitter.c:441
#6  0x00007fd5906c2ef6 in lj_BC_FUNCC () at buildvm_x86.dasc:857
#7  0x00007fd5906d5d43 in lua_pcall (L=L@entry=0x7fd59036f380, nargs=nargs@entry=2, nresults=nresults@entry=1, errfunc=errfunc@entry=-4)
    at /usr/src/debug/luajit/LuaJIT-5790d253972c9d78a0c2aece527eda5b134bbbf7/src/lj_api.c:1122
#8  0x000055c5e8a5e644 in nlua_pcall (lstate=0x7fd59036f380, nargs=2, nresults=1) at /usr/src/debug/neovim/neovim-0.9.5/src/nvim/lua/executor.c:159
#9  0x000055c5e8a6ed6c in nlua_call_ref (ref=<optimized out>, name=<optimized out>, args=..., retval=true, err=0x7ffe7b957c50) at /usr/src/debug/neovim/neovim-0.9.5/src/nvim/lua/executor.c:1580
#10 0x000055c5e8c16539 in decor_provider_invoke.constprop.0 (ns_id=16, name=name@entry=0x55c5e8c284a4 "buf", ref=<optimized out>, args=..., perr=perr@entry=0x55c5e8d0d8d8 <provider_err>, default_true=true)
    at /usr/src/debug/neovim/neovim-0.9.5/src/nvim/decoration_provider.c:36
#11 0x000055c5e8971562 in decor_providers_invoke_buf (buf=0x55c5eac1d9e0, providers=0x7ffe7b957e10, err=0x55c5e8d0d8d8 <provider_err>) at /usr/src/debug/neovim/neovim-0.9.5/src/nvim/decoration_provider.c:184
#12 0x000055c5e8988017 in update_screen () at /usr/src/debug/neovim/neovim-0.9.5/src/nvim/drawscreen.c:591
#13 0x000055c5e8ac5da1 in normal_redraw (s=0x7ffe7b957f00) at /usr/src/debug/neovim/neovim-0.9.5/src/nvim/normal.c:1329
#14 normal_check (state=0x7ffe7b957f00) at /usr/src/debug/neovim/neovim-0.9.5/src/nvim/normal.c:1422
#15 0x000055c5e8b96acf in state_enter (s=0x7ffe7b957f00) at /usr/src/debug/neovim/neovim-0.9.5/src/nvim/state.c:40
#16 0x000055c5e8ac0628 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at /usr/src/debug/neovim/neovim-0.9.5/src/nvim/normal.c:500
#17 0x000055c5e88ec781 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/neovim/neovim-0.9.5/src/nvim/main.c:642
```

### Output of `:checkhealth nvim-treesitter`

```markdown
Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v16.20.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20240417
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.1.90-1-MANJARO",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Fri May  3 05:13:01 UTC 2024"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1713773202
```

### Additional context

This happened after updating 
tree-sitter 0.20.10-2 0.22.6-1
Neovim 0.9.5-2 > 0.9.5-6

**Comment by clason** [comment]
Please report this at tree-sitter-vue (looking for existing -- open _and_ closed -- issues first, of course). This is a parser issue we can do nothing about.
